--- #YAML:1.0
name: HTML-Latemp-NavLinks-GenHtml
version: 0.1.5
license: bsd
distribution_type: module
requires:
  Class::Accessor: 0
  Template: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  HTML::Latemp::NavLinks::GenHtml:
    file: lib/HTML/Latemp/NavLinks/GenHtml.pm
    version: 0.1.5
  HTML::Latemp::NavLinks::GenHtml::ArrowImages:
    file: lib/HTML/Latemp/NavLinks/GenHtml/ArrowImages.pm
  HTML::Latemp::NavLinks::GenHtml::Text:
    file: lib/HTML/Latemp/NavLinks/GenHtml/Text.pm
generated_by: Module::Build version 0.21
