---
abstract: 'A module to generate the HTML of the'
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires: {}
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Latemp-NavLinks-GenHtml
provides:
  HTML::Latemp::NavLinks::GenHtml:
    file: lib/HTML/Latemp/NavLinks/GenHtml.pm
    version: v0.2.0
  HTML::Latemp::NavLinks::GenHtml::ArrowImages:
    file: lib/HTML/Latemp/NavLinks/GenHtml/ArrowImages.pm
    version: 0
  HTML::Latemp::NavLinks::GenHtml::Text:
    file: lib/HTML/Latemp/NavLinks/GenHtml/Text.pm
    version: 0
requires:
  Class::Accessor: 0
  Template: 0
  Test::More: 0
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
version: v0.2.0
