---
name: HTML-Latemp-NavLinks-GenHtml
version: 0.1.8
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
abstract: |-
  A module to generate the HTML of the 
  navigation links.
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  Class::Accessor: 0
  Template: 0
  Test::More: 0
provides:
  HTML::Latemp::NavLinks::GenHtml:
    file: lib/HTML/Latemp/NavLinks/GenHtml.pm
    version: 0.1.8
  HTML::Latemp::NavLinks::GenHtml::ArrowImages:
    file: lib/HTML/Latemp/NavLinks/GenHtml/ArrowImages.pm
  HTML::Latemp::NavLinks::GenHtml::Text:
    file: lib/HTML/Latemp/NavLinks/GenHtml/Text.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
