---
abstract: 'A module to generate the HTML of the'
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  Test::Differences: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.39'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Latemp-NavLinks-GenHtml
provides:
  HTML::Latemp::NavLinks::GenHtml:
    file: lib/HTML/Latemp/NavLinks/GenHtml.pm
    version: v0.2.3
  HTML::Latemp::NavLinks::GenHtml::ArrowImages:
    file: lib/HTML/Latemp/NavLinks/GenHtml/ArrowImages.pm
    version: v0.2.3
  HTML::Latemp::NavLinks::GenHtml::Text:
    file: lib/HTML/Latemp/NavLinks/GenHtml/Text.pm
    version: v0.2.3
requires:
  Class::Accessor: '0'
  Template: '0'
  parent: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.2.3
